all: help.out strlength.out strconcat.out strcompare.out

help.out: help.c
	gcc help.c -o help.out

mystrings.o: mystrings.c
	gcc -c mystrings.c -o mystrings.o


strlength.out: strlength.c mystrings.o
	gcc strlength.c mystrings.o -o strlength.out

strconcat.out: strlength.c mystrings.o strconcat.c
	gcc strconcat.c mystrings.o -o strconcat.out

strcompare.out: strlength.c mystrings.o strcompare.c
	gcc strcompare.c mystrings.o -o strcompare.out

clear:
	rm -f *.o *.out
 
	
