all: processes.o taskmanager.exe

processes.o: processes.c
	gcc -c processes.c -o processes.o

taskmanager.exe: taskmanager.c processes.o processes.c
	gcc taskmanager.c processes.o -o taskmanager.exe

clean:
	del *.o *.exe